### PR TITLE
Add git for versioning (via 'hook' in the config)

### PR DESCRIPTION
**Pull request by robertbeal**
Also added in using apk's virtual "group" dependencies for cleaner dependencies.

Git (although it could be anything) is an easy way to do versioning as per the radicale instructions:
http://radicale.org/versioning/

Hope it all looks ok. Great image btw.

### CODE REVIEW

**Comment by tomsquest** [comment]
Hi Robert,

Thanks a lot for your PR:
* Convenient to have a more complete image
* I learnt about virtual dependencies in Alpine

About your PR, I saw another commit about adding `openssh-client` but I do not see in your PR. Is it still required ?

**Comment by tomsquest** [comment]
@robertbeal can you confirm about `openssh-client` ?

**Comment by robertbeal** [comment]
Hey sorry, just back from holiday. Ah yeah I played around with putting openssh in but reverted the commit (and squashed it). 

I was thinking about adding a "push" to the hook (hence wanting an ssh client), but in the end decided it was better to do so outside of radicale.

**Comment by tomsquest** [comment]
Thanks @robertbeal

**Pull request merged**
