### PR TITLE
Define a Volume for the configuration

### LINKED ISSUE #5: Add volume for config
Hi,

it would be alot easier if we had a volume for the config file. Could you implement that?

### PR DESCRIPTION
**Pull request by tomsquest**
This PR closes #5

### CODE REVIEW

**Comment by tomsquest** [comment]
@robertbeal if you have the time to give a look...

**Comment by robertbeal** [comment]
Nice. Looks good. Only thing I can think of, which some people like and some don't, is to shorten the volume paths. `/config` for example but that'd be a breaking change.

**Comment by tomsquest** [comment]
Seems a good idea to have /config /data instead of /radicale/config|data.
WIll do that.

**Comment by tomsquest** [comment]
Seems a good idea to have /config /data instead of /radicale/config|data.
WIll do that.

**Pull request merged**
