### PR TITLE
fix: add ENV variables to handle ARG values during image build process on Synology NAS

### PR DESCRIPTION
**Pull request by adzero**
Submitting my changes to your Dockerfile after I finally succeeded building an image with custom UID/GID on my Synology NAS.  

Signed-off-by: AdZero <adzero.git@gmail.com>

### CODE REVIEW

**Comment by tomsquest** [comment]
Hi @adzero ,

Thanks for you PR.

So Synology does not allow to specify plain build-args ?

**Comment by adzero** [comment]
Hi @tomsquest 

I tried building this image on my Synology shell. 
I made multiple tests adding intermediate RUN echo to display arg values whether with their default or command line value.  Every declared ARG values stays empty, even with default value only (as the VERSION arg which is the first to cause problem in the build process). 

I checked online for solutions but the only reccurrent case is for ARG declarations before FROM as [detailed here](https://benkyriakou.com/posts/docker-args-empty). 
In your Dockerfile ARG declaration are after the one and only FROM statement, so that is irrelevant. 

For now, the only solution I found is to pass ARG values to ENV variables to be able to make the build process work. 

I haven't found info about such limitation on Synology OS. 

Have you recently built successfully an image with custom UID/GID on the command line ?
If yes, what is your Docker version ?

Thanks.

**Comment by adzero** [comment]
I finally found something on the Synology forum : https://community.synology.com/enu/forum/1/post/128146

Docker compose is mentioned in the title but problem seems to be spread among other docker binaries. 

Feel free to decline my pull request as it is specific to Synology users. 

Thanks.

**Comment by tomsquest** [comment]
Hi @adzero ,

I have no problem with your PR. 
Re-reading Docker's Dockerfile reference about ARG ( https://docs.docker.com/engine/reference/builder/#using-arg-variables ) , you can use the same name for ARG and ENV, similar to :

```bash
ARG UID
ENV UID ${UID:-2999}
```

That will avoid prefixing env vars by `ENV_`.

Can you make the change ?

**Comment by adzero** [comment]
Hi @tomsquest, 

yes I can do the changes. 
Actually, I've already done them but I noticed that adding ENV variables with UID or GID names prevents the container to start (GID) or triggers output in stderr. 

For UID variable, I have a log stating : 

```
usermod: no changes
```

For GID variable, I have the two log lines in : 

```
groupmod: cannot open /etc/group
groupmod: failed to unlock /etc/group
```
I don't know if it's another bug or limitation of Synology's Docker package. 

The solution to this is to change the name of the two variables to, for instance, PUID and PGID. 

Beginning of the Dockerfile would be : 

```
FROM alpine:3.10

ARG COMMIT_ID
ARG VERSION
ARG PUID
ARG PGID

ENV COMMIT_ID ${COMMIT_ID}
ENV VERSION ${VERSION:-2.1.11}
ENV PUID ${PUID:-2999}
ENV PGID ${PGID:-2999}

LABEL maintainer="Thomas Queste <tom@tomsquest.com>"
...
```
If you're OK with this, I'll make a new PR with these changes to Dockerfile and README.

**Comment by tomsquest** [comment]
Oh you answered a question I had reading a bunch of linuxserver Docker images ! "But why are they using `PUID` and `PGID` as the variable names?". 
The existing `UID` and `GID` are shadowed if the image uses them !

So, GO for your solution with PUID and PGID. 

Your PR will improve this project, and this is really appreciated. :+1:

**Comment by adzero** [comment]
Hi @tomsquest ,

As I said in my last comment, I updated both Dockerfile and README keeping the same commit to avoid making a new PR. 
So everything should be OK for you to merge after you review my changes.

Thanks.

**Comment by tomsquest** [comment]
Thanks @adzero !

**Pull request merged**
